"""3D lifting backends for the pose-3d node (REQ-2).

Backends convert a list of :class:`Keypoints2D` frames into a list of
:class:`Keypoints3D` frames. The default ``SyntheticLiftingBackend`` is
deterministic (CI truth); ``HeuristicLiftingBackend`` adds anthropometric
depth; ``OnnxLiftingBackend`` lifts through the MotionBERT ONNX model
(``models/motionbert.onnx``, generated by
``tools/export_motionbert_onnx.py``). ``depth_mode`` values multiply the depth
deviation; unknown values degrade to the default (spec REQ-2/REQ-3).
"""

from __future__ import annotations

import math
from pathlib import Path
from typing import TYPE_CHECKING, Any, Protocol, runtime_checkable

import numpy as np

from aimation_actor_core.domain.animation.keypoints import Keypoint, Keypoints2D
from aimation_actor_core.domain.animation.keypoints3d import Keypoint3D, Keypoints3D

if TYPE_CHECKING:
    from aimation_actor_core.infrastructure.models.registry import ModelRegistry

#: Depth-deviation multiplier per ``depth_mode``. ``proportional`` is the
#: default; ``flat`` collapses every joint onto the camera plane.
DEPTH_MODES: dict[str, float] = {"proportional": 1.0, "flat": 0.0}

#: z values around the camera plane (0.5) per COCO label — documented table:
#: torso/head joints sit on the camera plane (0.5); wrists/ankles deviate to
#: 0.55-0.65 (farther from the camera); elbows/knees sit between.
Z_TABLE: dict[str, float] = {
    "nose": 0.50,
    "left_eye": 0.50,
    "right_eye": 0.50,
    "left_ear": 0.50,
    "right_ear": 0.50,
    "left_shoulder": 0.50,
    "right_shoulder": 0.50,
    "left_hip": 0.50,
    "right_hip": 0.50,
    "left_elbow": 0.55,
    "right_elbow": 0.55,
    "left_knee": 0.55,
    "right_knee": 0.55,
    "left_wrist": 0.60,
    "right_wrist": 0.60,
    "left_ankle": 0.65,
    "right_ankle": 0.65,
}

#: Camera-plane z used for labels absent from :data:`Z_TABLE`.
DEFAULT_Z = 0.50

#: Per-joint depth priors (camera plane = 0.5) for the heuristic backend.
DEPTH_PRIOR: dict[str, float] = {
    "nose": 0.50,
    "left_eye": 0.50,
    "right_eye": 0.50,
    "left_ear": 0.50,
    "right_ear": 0.50,
    "left_shoulder": 0.50,
    "right_shoulder": 0.50,
    "left_hip": 0.50,
    "right_hip": 0.50,
    "left_elbow": 0.53,
    "right_elbow": 0.53,
    "left_knee": 0.53,
    "right_knee": 0.53,
    "left_wrist": 0.56,
    "right_wrist": 0.56,
    "left_ankle": 0.60,
    "right_ankle": 0.60,
}

DEFAULT_PRIOR = 0.50

#: Gain scaling how strongly a joint's vertical position (y) and the person's
#: 2D scale push z away from the camera plane.
Y_DRIFT_GAIN = 0.30

#: Person-scale fallback when shoulder keypoints are missing.
DEFAULT_SCALE = 0.50

#: Adjacent joint pairs used by the bone-length consistency clamp.
BONES: list[tuple[str, str]] = [
    ("left_shoulder", "left_elbow"),
    ("right_shoulder", "right_elbow"),
    ("left_elbow", "left_wrist"),
    ("right_elbow", "right_wrist"),
    ("left_hip", "left_knee"),
    ("right_hip", "right_knee"),
    ("left_knee", "left_ankle"),
    ("right_knee", "right_ankle"),
    ("left_shoulder", "left_hip"),
    ("right_shoulder", "right_hip"),
]

#: |dz| along a bone may not exceed this fraction of the observed 2D bone length.
BONE_Z_CLAMP_RATIO = 0.50


# ===== MotionBERT ONNX constants ==============================================

#: Manifest model key for the MotionBERT ONNX lifting model.
MOTIONBERT_MODEL_NAME = "motionbert"

#: Default model path for :class:`OnnxLiftingBackend` (repo-root relative).
MOTIONBERT_MODEL_PATH = "models/motionbert.onnx"

#: Maximum frames per inference window. The exported DSTformer is anchored to
#: ``maxlen=243`` (``MODEL_KWARGS`` in ``tools/export_motionbert_onnx.py``):
#: the ONNX frame axis is dynamic only at the boundary, so internal
#: broadcasts break on longer inputs (a 795-frame video fails with
#: "Attempting to broadcast an axis by a dimension other than 1 ... 243 by
#: 795"). ``OnnxLiftingBackend.lift`` feeds the model contiguous windows of
#: at most this many frames and concatenates the results.
_MAX_SEQ_LEN = 243

#: H36M-17 joint order consumed by the MotionBERT model. Note this is the
#: model's internal order (H36M), NOT COCO-17: ``root`` is the mid-hip joint,
#: ``belly``/``neck`` are midpoint joints and ``head`` is the head-top
#: keypoint. COCO-17 frames must be re-ordered/synthesized into this layout
#: (see ``_build_h36m_frame``).
MOTIONBERT_H36M_LABELS: list[str] = [
    "root",
    "right_hip",
    "right_knee",
    "right_ankle",
    "left_hip",
    "left_knee",
    "left_ankle",
    "belly",
    "neck",
    "nose",
    "head",
    "left_shoulder",
    "left_elbow",
    "left_wrist",
    "right_shoulder",
    "right_elbow",
    "right_wrist",
]

#: Index of each H36M label inside :data:`MOTIONBERT_H36M_LABELS`.
_H36M_INDEX: dict[str, int] = {
    label: index for index, label in enumerate(MOTIONBERT_H36M_LABELS)
}

#: Mapping from COCO-17 labels to their H36M row index. The four remaining
#: H36M joints (root, belly, neck, head) have no direct COCO counterpart and
#: are synthesized as geometric midpoints (see ``_build_h36m_frame``).
_COCO_TO_H36M: dict[str, int] = {
    "nose": _H36M_INDEX["nose"],
    "left_shoulder": _H36M_INDEX["left_shoulder"],
    "right_shoulder": _H36M_INDEX["right_shoulder"],
    "left_elbow": _H36M_INDEX["left_elbow"],
    "right_elbow": _H36M_INDEX["right_elbow"],
    "left_wrist": _H36M_INDEX["left_wrist"],
    "right_wrist": _H36M_INDEX["right_wrist"],
    "left_hip": _H36M_INDEX["left_hip"],
    "right_hip": _H36M_INDEX["right_hip"],
    "left_knee": _H36M_INDEX["left_knee"],
    "right_knee": _H36M_INDEX["right_knee"],
    "left_ankle": _H36M_INDEX["left_ankle"],
    "right_ankle": _H36M_INDEX["right_ankle"],
}

#: Install hint surfaced when the MotionBERT model file is missing; the
#: exporter is the canonical way to generate it.
_MOTIONBERT_INSTALL_HINT = (
    "MotionBERT ONNX model not found at {path}. Generate it with: "
    "`python tools/export_motionbert_onnx.py`"
)


def depth_multiplier(depth_mode: str) -> float:
    """Resolve a ``depth_mode`` name to a deviation multiplier.

    Unknown values resolve to the default ``proportional`` (1.0), per spec
    REQ-2 ("unknown depth_mode -> defaults").
    """
    return DEPTH_MODES.get(depth_mode, 1.0)


def _clamp(value: float, low: float = 0.0, high: float = 1.0) -> float:
    """Clamp ``value`` into ``[low, high]``."""
    return min(high, max(low, value))


@runtime_checkable
class LiftingBackend(Protocol):
    """Protocol for 3D lifting backends (spec REQ-2)."""

    def lift(self, keypoints_2d: list[Keypoints2D]) -> list[Keypoints3D]:
        """Lift 2D keypoints into normalized 3D keypoints.

        Args:
            keypoints_2d: Input frames, one :class:`Keypoints2D` per frame.

        Returns:
            One :class:`Keypoints3D` per input frame, minus confidence-filtered
            joints applied by the caller; empty input yields [].
        """
        ...


class SyntheticLiftingBackend:
    """Deterministic per-joint z-table lifting (default backend, REQ-2).

    Every joint keeps its 2D ``x``/``y`` geometry, gets a fixed ``z`` from
    :data:`Z_TABLE` (deviation from 0.5 multiplied by the ``depth_mode``
    multiplier, clamped to [0, 1]), confidence 0.95 and ``visible=True``.
    """

    def __init__(self, depth_mode: str = "proportional") -> None:
        self._multiplier = depth_multiplier(depth_mode)

    def lift(self, keypoints_2d: list[Keypoints2D]) -> list[Keypoints3D]:
        """Lift every frame deterministically from the z-table."""
        frames: list[Keypoints3D] = []
        for kp2d in keypoints_2d:
            keypoints = [
                Keypoint3D(
                    label=kp.label,
                    x=kp.x,
                    y=kp.y,
                    z=_clamp(
                        DEFAULT_Z
                        + (Z_TABLE.get(kp.label, DEFAULT_Z) - DEFAULT_Z) * self._multiplier
                    ),
                    confidence=0.95,
                    visible=True,
                )
                for kp in kp2d.keypoints
            ]
            frames.append(Keypoints3D(frame_index=kp2d.frame_index, keypoints=keypoints))
        return frames


class HeuristicLiftingBackend:
    """Anthropometric depth lifting (REQ-2).

    Person scale is estimated from the 2D shoulder extent; per-joint depth
    priors drift with vertical position (y) and scale; bone-length consistency
    clamps keep 3D joint spread plausible; final clamp keeps z in [0, 1].
    Deterministic given the input.
    """

    def __init__(self, depth_mode: str = "proportional") -> None:
        self._multiplier = depth_multiplier(depth_mode)

    def lift(self, keypoints_2d: list[Keypoints2D]) -> list[Keypoints3D]:
        """Lift every frame using heuristics over its 2D geometry."""
        frames: list[Keypoints3D] = []
        for kp2d in keypoints_2d:
            by_label = {kp.label: kp for kp in kp2d.keypoints}
            if not by_label:
                # Missing labels: empty per-frame output, never crash (REQ-2).
                frames.append(Keypoints3D(frame_index=kp2d.frame_index, keypoints=[]))
                continue
            scale = self._person_scale(by_label)
            keypoints = [self._lift_joint(kp, scale) for kp in kp2d.keypoints]
            keypoints = self._clamp_bones(keypoints)
            frames.append(Keypoints3D(frame_index=kp2d.frame_index, keypoints=keypoints))
        return frames

    def _person_scale(self, by_label: dict[str, Keypoint]) -> float:
        """Estimate person scale from the 2D shoulder separation."""
        left = by_label.get("left_shoulder")
        right = by_label.get("right_shoulder")
        if left is not None and right is not None:
            return abs(left.x - right.x)
        return DEFAULT_SCALE

    def _lift_joint(self, kp: Keypoint, scale: float) -> Keypoint3D:
        """Lift a single 2D joint into 3D.

        ``z`` = prior + (y - 0.5) * scale * gain, whole deviation multiplied
        by the ``depth_mode`` multiplier, then clamped to [0, 1].
        """
        raw_z = DEPTH_PRIOR.get(kp.label, DEFAULT_PRIOR) + (kp.y - 0.5) * scale * Y_DRIFT_GAIN
        z = _clamp(DEFAULT_Z + (raw_z - DEFAULT_Z) * self._multiplier)
        return Keypoint3D(
            label=kp.label,
            x=kp.x,
            y=kp.y,
            z=z,
            confidence=kp.confidence,
            visible=True,
        )

    def _clamp_bones(self, keypoints: list[Keypoint3D]) -> list[Keypoint3D]:
        """Clamp z-spread along known bones to the observed 2D bone length.

        Iterates :data:`BONES` in fixed order, so the result is deterministic.
        """
        by_label = {kp.label: kp for kp in keypoints}
        for label_a, label_b in BONES:
            a = by_label.get(label_a)
            b = by_label.get(label_b)
            if a is None or b is None:
                continue
            bone_2d = math.hypot(a.x - b.x, a.y - b.y)
            if bone_2d <= 1e-9:
                continue
            limit = BONE_Z_CLAMP_RATIO * bone_2d
            z_b = _clamp(b.z, a.z - limit, a.z + limit)
            if z_b != b.z:
                by_label[label_b] = Keypoint3D(
                    label=b.label,
                    x=b.x,
                    y=b.y,
                    z=z_b,
                    confidence=b.confidence,
                    visible=b.visible,
                )
        # Every keypoint label is present in ``by_label`` (it was built from
        # the same list), so this preserves input order with clamped z values.
        return [by_label[kp.label] for kp in keypoints]


def _midpoint_tuple(
    a: tuple[float, float, float], b: tuple[float, float, float]
) -> tuple[float, float, float]:
    """Midpoint of two (x, y, confidence) tuples, zeros when either is absent.

    Confidence is the minimum of the two sources; an all-zero tuple counts as
    absent (confidence 0), mirroring the presence convention of COCO→H36M
    conversion (``posetrack2h36m`` in ``dataset_motion_2d.py``).
    """
    if a[2] <= 0 or b[2] <= 0:
        return (0.0, 0.0, 0.0)
    return ((a[0] + b[0]) / 2.0, (a[1] + b[1]) / 2.0, min(a[2], b[2]))


def _build_h36m_frame(keypoints: list[Keypoint]) -> np.ndarray:
    """Map one COCO-17 frame into the model's (17, 3) H36M-order array.

    Direct joints are copied 1:1 (only when confidence > 0); the four H36M
    joints without a COCO counterpart are synthesized as geometric midpoints:
    ``root`` = mid-hip, ``neck`` = mid-shoulder, ``belly`` = mid(root, neck),
    ``head`` = mid(nose, ears). A synthesized joint is all-zeros (treated as
    absent by ``crop_scale``) when either source is missing or has confidence
    0.

    Returns:
        Float32 (17, 3) array — columns x / y / confidence — in
        :data:`MOTIONBERT_H36M_LABELS` order.
    """
    by_label = {kp.label: kp for kp in keypoints}

    def tuple_of(label: str) -> tuple[float, float, float]:
        kp = by_label.get(label)
        if kp is None:
            return (0.0, 0.0, 0.0)
        return (kp.x, kp.y, kp.confidence)

    root = _midpoint_tuple(tuple_of("left_hip"), tuple_of("right_hip"))
    neck = _midpoint_tuple(tuple_of("left_shoulder"), tuple_of("right_shoulder"))
    belly = _midpoint_tuple(root, neck)
    ears = _midpoint_tuple(tuple_of("left_ear"), tuple_of("right_ear"))
    head = _midpoint_tuple(tuple_of("nose"), ears)

    frame = np.zeros((17, 3), dtype=np.float32)
    frame[_H36M_INDEX["root"]] = root
    frame[_H36M_INDEX["belly"]] = belly
    frame[_H36M_INDEX["neck"]] = neck
    frame[_H36M_INDEX["head"]] = head
    for label, index in _COCO_TO_H36M.items():
        kp = by_label.get(label)
        if kp is not None and kp.confidence > 0:
            frame[index] = (kp.x, kp.y, kp.confidence)
    return frame


def _crop_scale_motion(motion: np.ndarray) -> tuple[np.ndarray, float]:
    """Normalize a (F, 17, 3) motion to the model's wild-input convention.

    Clones ``crop_scale`` from ``lib/utils/utils_data.py`` at the pinned
    MotionBERT commit ``705d3a95354db8bdb696b3492e47a3b5537174ff`` with
    ``scale_range=[1, 1]`` (deterministic — no sampling): joints with
    confidence != 0 define the bounding box, ``scale = max(x-range, y-range)``,
    coordinates are centered on it, divided by ``scale``, mapped from
    [0, 1] to [-1, 1] and clipped. Rows with confidence 0 are zeroed
    afterwards, mirroring ``dataset_motion_2d.py``.

    Args:
        motion: (F, 17, 3) float32 array, columns x / y / confidence.

    Returns:
        (normalized (F, 17, 3) array, bbox ``scale``). ``scale`` is 0.0 when
        fewer than 4 joints are valid, in which case the caller must skip
        inference.
    """
    result = motion.copy()
    valid_coords = motion[motion[..., 2] != 0][:, :2]
    if len(valid_coords) < 4:
        return np.zeros(motion.shape, dtype=np.float32), 0.0
    xmin = float(valid_coords[:, 0].min())
    xmax = float(valid_coords[:, 0].max())
    ymin = float(valid_coords[:, 1].min())
    ymax = float(valid_coords[:, 1].max())
    scale = max(xmax - xmin, ymax - ymin)
    if scale <= 0.0:
        return np.zeros(motion.shape, dtype=np.float32), 0.0
    xs = (xmin + xmax - scale) / 2.0
    ys = (ymin + ymax - scale) / 2.0
    result[..., :2] = (result[..., :2] - np.asarray([xs, ys], dtype=np.float32)) / scale
    result[..., :2] = (result[..., :2] - 0.5) * 2.0
    np.clip(result[..., :2], -1.0, 1.0, out=result[..., :2])
    result[result[..., 2] == 0] = 0.0
    return result.astype(np.float32), scale


def _map_z_to_domain(z_model: np.ndarray, z_root: np.ndarray, scale: float) -> np.ndarray:
    """Map the model's z channel into the domain's [0, 1] camera-plane z.

    The model emits z in H36M camera-normalized units (the spatial units of
    its crop-scaled input): the root joint (mid-hip, index 0) sits at ~0 and
    joints *away from* the camera are positive. Domain convention: 0.5 =
    camera plane, farther = larger.

    ``z_domain = 0.5 + (z_model - z_root) / z_scale`` with
    ``z_scale = 2 / scale``: the crop-scale transform
    ``x_n = (x - xs) / scale * 2 - 1`` maps one image-normalized unit to
    ``2 / scale`` model units, so dividing by ``z_scale`` converts model units
    back to image-normalized units — z ends up in the same units as x/y
    (verified against ``models/motionbert.onnx``: a standing fixture lands in
    the plausible band head ~0.44 / ankles ~0.56).

    Args:
        z_model: (F, 17) model z output.
        z_root: (F, 1) root-joint z per frame.
        scale: crop-scale bbox extent in image-normalized units.

    Returns:
        (F, 17) z values clamped to [0, 1].
    """
    z_rel = z_model - z_root
    z_domain: np.ndarray = np.clip(0.5 + z_rel / (2.0 / scale), 0.0, 1.0)
    return z_domain


class OnnxLiftingBackend:
    """MotionBERT ONNX Runtime 3D lifting backend (REQ-2).

    Frames are converted to the model's H36M-17 joint order, normalized with
    ``crop_scale`` (the official in-the-wild convention, ``scale_range=[1, 1]``
    — deterministic), and each joint's model z is mapped back domain-side with
    the root-relative convention (mid-hip root at 0.5 = camera plane).

    The transformer is anchored to ``maxlen=243`` frames internally, so
    sequences are fed in contiguous windows of at most ``_MAX_SEQ_LEN`` frames
    and the per-window z results are concatenated.

    onnxruntime is imported at construction time so a missing package surfaces
    a clear ImportError (REQ-2); the model file itself loads lazily on the
    first ``lift()`` call.
    """

    def __init__(self, model_path: str | Path = MOTIONBERT_MODEL_PATH) -> None:
        """Initialize the backend with a model path.

        Args:
            model_path: Path to the ONNX model file.

        Raises:
            ImportError: If onnxruntime is not installed.
        """
        self.model_path = Path(model_path)
        try:
            import onnxruntime  # type: ignore[import-untyped]  # noqa: F401
        except ImportError as e:
            raise ImportError(
                "onnxruntime is required for OnnxLiftingBackend but is not installed. "
                "Install it with: pip install onnxruntime"
            ) from e
        self._session: Any = None
        self._input_name = ""

    @classmethod
    def from_registry(cls, registry: ModelRegistry | None = None) -> OnnxLiftingBackend:
        """Build a backend from the registry's ``motionbert`` model entry.

        Args:
            registry: Model registry to resolve the model from; defaults to a
                fresh registry rooted at the repo ``models/`` directory.

        Raises:
            ModelManifestError: If the manifest is missing or has no
                ``motionbert`` entry.
        """
        if registry is None:
            from aimation_actor_core.infrastructure.models.registry import ModelRegistry

            registry = ModelRegistry()
        spec = registry.get(MOTIONBERT_MODEL_NAME)
        return cls(model_path=registry.installed_path(spec))

    def _ensure_session(self) -> Any:  # noqa: ANN401 — onnxruntime session is untyped
        """Load and cache the onnxruntime inference session.

        Raises:
            FileNotFoundError: If the model file does not exist, with an
                install hint pointing at the exporter.
        """
        if self._session is not None:
            return self._session
        if not self.model_path.exists():
            raise FileNotFoundError(_MOTIONBERT_INSTALL_HINT.format(path=self.model_path))
        import onnxruntime

        providers = ["CPUExecutionProvider"]
        session = onnxruntime.InferenceSession(str(self.model_path), providers=providers)
        self._input_name = session.get_inputs()[0].name
        self._session = session
        return session

    def lift(self, keypoints_2d: list[Keypoints2D]) -> list[Keypoints3D]:
        """Lift 2D frames into 3D with the MotionBERT ONNX model.

        Args:
            keypoints_2d: Input frames, one :class:`Keypoints2D` per frame.

        Raises:
            FileNotFoundError: If the model file is missing.

        Returns:
            One :class:`Keypoints3D` per input frame; [] for empty input
            (nothing is loaded or inferred in that case).
        """
        if not keypoints_2d:
            return []
        session = self._ensure_session()
        motion = np.asarray(
            [_build_h36m_frame(kp2d.keypoints) for kp2d in keypoints_2d], dtype=np.float32
        )
        normalized, scale = _crop_scale_motion(motion)
        if scale > 0.0:
            # Feed contiguous windows of at most _MAX_SEQ_LEN frames: the
            # exported transformer is anchored to maxlen=243 internally, so a
            # single call on a longer sequence breaks broadcasts (see the
            # constant's comment). The bbox scale stays global — every window
            # maps back with the same convention as the single-call path.
            z_chunks: list[np.ndarray] = []
            for start in range(0, len(normalized), _MAX_SEQ_LEN):
                window = normalized[start : start + _MAX_SEQ_LEN]
                (outputs,) = session.run(None, {self._input_name: window[np.newaxis, ...]})
                z_model = np.asarray(outputs, dtype=np.float32)[0, :, :, 2]
                root_index = _H36M_INDEX["root"]
                z_root = z_model[:, root_index : root_index + 1]
                z_chunks.append(_map_z_to_domain(z_model, z_root, scale))
            z_domain = np.concatenate(z_chunks, axis=0)
        else:
            # Fewer than 4 valid joints: the sequence cannot be normalized, so
            # skip inference and keep every joint on the camera plane.
            z_domain = None
        frames: list[Keypoints3D] = []
        for frame_index, kp2d in enumerate(keypoints_2d):
            frame_z = None if z_domain is None else z_domain[frame_index]
            frames.append(self._lift_frame(kp2d, frame_z))
        return frames

    def _lift_frame(self, kp2d: Keypoints2D, z_domain: np.ndarray | None) -> Keypoints3D:
        """Assemble one output frame from the input keypoints and model z."""
        if not kp2d.keypoints:
            return Keypoints3D(frame_index=kp2d.frame_index, keypoints=[])
        keypoints = [
            Keypoint3D(
                label=kp.label,
                x=kp.x,
                y=kp.y,
                z=self._joint_z(kp, z_domain),
                confidence=kp.confidence,
                visible=kp.confidence > 0,
            )
            for kp in kp2d.keypoints
        ]
        return Keypoints3D(frame_index=kp2d.frame_index, keypoints=keypoints)

    def _joint_z(self, kp: Keypoint, z_domain: np.ndarray | None) -> float:
        """Domain z for one joint: model z when available, else camera plane.

        Joints without a model row (eyes, ears, unknown labels) and joints
        with zero confidence stay on the camera plane (0.5).
        """
        index = _COCO_TO_H36M.get(kp.label)
        if kp.confidence <= 0 or index is None or z_domain is None:
            return DEFAULT_Z
        return _clamp(float(z_domain[index]))
